<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Redis providers for idunno.Bluesky.AspNet.Authentication.</Description>
    <PackageTags>atproto;bluesky;aspnetcore;authentication;security;redis</PackageTags>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
    <NeutralLanguage>en-US</NeutralLanguage>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="PublicAPI.Shipped.txt" />
    <AdditionalFiles Include="PublicAPI.Unshipped.txt" />
  </ItemGroup>

  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="\" />
    <None Include="..\idunno.Bluesky.AspNet.Authentication\icon.png" Link="icon.png" Pack="true" PackagePath="\" />
    <None Include="..\..\exclusion.dic" Link="exclusion.dic" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\idunno.Bluesky.AspNet.Authentication\idunno.Bluesky.AspNet.Authentication.csproj" />
  </ItemGroup>

</Project>
