//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace idunno.Bluesky.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("idunno.Bluesky.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add a video to a post that already has images..
        /// </summary>
        internal static string CannotAddVideoToPostWithImages {
            get {
                return ResourceManager.GetString("CannotAddVideoToPostWithImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post text cannot be null or empty unless there are images, video or another type of embedded record..
        /// </summary>
        internal static string EmptyPostTextValidationError {
            get {
                return ResourceManager.GetString("EmptyPostTextValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only strong references to records of collection &apos;app.bsky.feed.post&apos; can be quoted..
        /// </summary>
        internal static string PostBuilderAddQuoteToNonPostError {
            get {
                return ResourceManager.GetString("PostBuilderAddQuoteToNonPostError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post cannot contain both images and gallery images..
        /// </summary>
        internal static string PostBuilderCannotHaveImagesAndGalleryImages {
            get {
                return ResourceManager.GetString("PostBuilderCannotHaveImagesAndGalleryImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have more than {0} gallery images..
        /// </summary>
        internal static string PostBuilderHasTooManyGalleryImages {
            get {
                return ResourceManager.GetString("PostBuilderHasTooManyGalleryImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have more than {0} images..
        /// </summary>
        internal static string PostBuilderHasTooManyImages {
            get {
                return ResourceManager.GetString("PostBuilderHasTooManyImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post cannot have both images and video..
        /// </summary>
        internal static string PostCannotHaveImagesAndVideoValidationError {
            get {
                return ResourceManager.GetString("PostCannotHaveImagesAndVideoValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post contains self labels but no media.
        /// </summary>
        internal static string PostHasLabelsButNoMediaValidationError {
            get {
                return ResourceManager.GetString("PostHasLabelsButNoMediaValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post text cannot be longer than {0} graphemes..
        /// </summary>
        internal static string PostTextExceedsMaxLengthInGraphemesValidationError {
            get {
                return ResourceManager.GetString("PostTextExceedsMaxLengthInGraphemesValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have a length greater than {0} characters, or {1} graphemes..
        /// </summary>
        internal static string PostTextExceedsMaxLengths {
            get {
                return ResourceManager.GetString("PostTextExceedsMaxLengths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post text cannot be longer than {0} characters..
        /// </summary>
        internal static string PostTextExceedsMaxLengthValidationError {
            get {
                return ResourceManager.GetString("PostTextExceedsMaxLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Parent and/or Root references do not point to an &apos;app.bsky.feed.post&apos; record(s).
        /// </summary>
        internal static string ReplyReferencesDoNotPointToPostRecord {
            get {
                return ResourceManager.GetString("ReplyReferencesDoNotPointToPostRecord", resourceCulture);
            }
        }
    }
}
