<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <Description>idunno.Bluesky.AspNet.Authentication.UI is the default Razor Pages UI for Bluesky authentication.</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageTags>atproto;bluesky;aspnetcore;authentication;security;razorpages</PackageTags>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <StaticWebAssetBasePath>Bluesky</StaticWebAssetBasePath>
  </PropertyGroup>

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\idunno.Bluesky.AspNet.Authentication\idunno.Bluesky.AspNet.Authentication.csproj" />
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
