<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <Description>idunno.Bluesky.AspNet.Authentication.UI is the default Razor Pages UI for Bluesky authentication.</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageTags>atproto;bluesky;aspnetcore;authentication;security;razorpages</PackageTags>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <StaticWebAssetBasePath>Bluesky</StaticWebAssetBasePath>
    <IsTrimmable>false</IsTrimmable>
    <IsAotCompatible>false</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- Nuget package properties -->
  <PropertyGroup>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
    <NeutralLanguage>en-US</NeutralLanguage>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0|AnyCPU'">
    <WarningLevel>8</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0|AnyCPU'">
    <WarningLevel>8</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='CodeQL|net9.0|AnyCPU'">
    <WarningLevel>8</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0|AnyCPU'">
    <WarningLevel>8</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0|AnyCPU'">
    <WarningLevel>8</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='CodeQL|net10.0|AnyCPU'">
    <WarningLevel>8</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="\" />
    <None Include="icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\idunno.Bluesky.AspNet.Authentication\idunno.Bluesky.AspNet.Authentication.csproj" />
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
