<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\idunno.Bluesky\idunno.Bluesky.csproj" />
    <ProjectReference Include="..\Samples.Common\Samples.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="sample.mp4">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
