name: Markdown Links Check

on:
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: 'Check for dead links in markdown files'
        uses: gaurav-nelson/github-action-markdown-link-check@d53a906aa6b22b8979d33bc86170567e619495ec # v1.0.15
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
