name: Add code coverage summary to PRs

# Allows code coverage comments to be embedded in PRs if the build was ran on a fork.

on:
  workflow_run:
    workflows: ["ci-build"]
    types:
      - completed

jobs:
  prCoverageComment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: 
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
      with:
        egress-policy: audit

    - name: 'Download coverage results'
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: coverage-results

    - name: Add Code Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@d2ad0de260ae8b0235ce059e63f2949ba9e05943 # v2.9.3
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
